services:
  product:
    image: "${DOCKER_REPO}:${BRANCH}-latest"  # Use env variable
    container_name: "product_frontend_${BRANCH}"
    ports:
      - "172.17.0.1:${EXT_PORT}:${APP_PORT}"
    restart: always
